### ISSUE TITLE
When using sortBy aggregatePaginate returns same results over different pages 

### ISSUE THREAD

**Issue by ldevalbray** [Maheshkumar-Kakade/mongoose-aggregate-paginate#17] opened 2017-12-09 15:14 UTC
See this stackoverflow issue : https://stackoverflow.com/questions/47720144/mongodb-mongoose-aggregatepagination-returns-multiple-same-documents-over-differ?noredirect=1#comment82403985_47720144

Thank you for your time !

**Comment by ldevalbray** [comment] 2017-12-09 22:36
@Maheshkumar-Kakade  I would reeeaaally appreciate your help :)

**Comment by Maheshkumar-Kakade** [comment] 2017-12-10 01:24
Will you please specify nodejs and mongodb , mongoose version? It will be helpful if you give me sample data.

**Comment by ldevalbray** [comment] 2017-12-10 10:22
Sure thing ! 
"mongodb": "^2.2.28",
"mongoose": "4.10.2",
"express": "^4.15.3"
and the latest nodejs

**Comment by ldevalbray** [comment] 2017-12-10 10:27
Here are the users id I get when asking for page 1 with 8 users per page : 
["59e06a6ea910b1001d5284f2", "59f7680f566602001dddf99f", "59f76900566602001dddf9a5", "59f77622566602001dddf9c7", "59f787c5566602001dddf9d4", "59f9a4394b4b3d001dfc2bfc", "59fb2e9aae1b56001d2d6479", "59fb7cbad364e0001d1a8ef4"]

When asking for page 2 : 
["59e06a6ea910b1001d5284f2", "59e8941deaa275001d55e7d3", "59f76900566602001dddf9a5", "59f77622566602001dddf9c7", "59f787c5566602001dddf9d4", "59ecc29cae484e001d61cef6", "59ede89ddf186e001de34a59", "59f07f16204549001d26c6d3"]

I get 4 new users and 4 already there in the previous page. The numbers are quite random, I can get 2 new users and 6 already there ...

When I remove "sortBy", everything works correctly

**Comment by ldevalbray** [comment] 2017-12-12 12:40
Let me know if you need anything else :)

**Comment by ldevalbray** [comment] 2017-12-18 18:20
@Maheshkumar-Kakade  Any updates ? :)

**Comment by ldevalbray** [comment] 2018-01-16 16:03
@Maheshkumar-Kakade Any updates ? :)

**Comment by Maheshkumar-Kakade** [comment] 2018-01-27 08:01
Sorry for late response. I am not able to reproduce issue with data in test cases. Have tried using different sort field? It is possible that sort will not return same values if updatedDate is same for all records.

**Comment by ldevalbray** [comment] 2018-02-10 11:03
Hello, Would it be possible that the bug occurs because I try to sort by "updatedDate" and some of the objects don't have any ?

**Comment by ldevalbray** [comment] 2018-03-16 11:10
Hello there, here is the model of the objects I try to sort. Could you try to reproduce the issue with this model ?

```
var tutorSchema = mongoose.Schema({
	fullName: {
		type: String,
		trim: true,
		minlength: [1, 'Full name can not be empty'],
		required: [true, 'Full name is required']
	},
	location: {
		address_components: [
			{
				long_name: String,
				short_name: String,
				types: String
			}
		],
		description: String,
		lat: Number,
		lng: Number

	},
	loc: {
		type: { type: String },
		coordinates: []
	},
	telephoneNumber: {
		type: String,
		trim: true,
		validate: telephoneNumberValidator,
		required: [true, 'Phone number is required']
	},
	dob: {
		type: Date,
		required: [true, 'Date of birth is required']
	},
	createdAt: {
		type: Date,
		required: [true, 'Account creation date is required'],
		default: Date.now
	},
	updatedDate: {
		type: Date,
		required: [true, 'Account updated date is required'],
		default: Date.now
	},
	expireAt: {
		type: Date,
		default: undefined
	},
	levels: [
		{
			type: ObjectId,
			ref: 'Level',
			required: [true, 'Level is required'],
			validate: levelValidator
		}
	],
	profileOnline: {
		type: Boolean,
		default: true
	},
	range: {
		type: Number,
		default: 5,
		validate: rangeValidator
	},
	bio: String,
	hobbies: [String],
	profileActivated: {
		type: Boolean,
		default: false
	},
	experiences: [
		{
			intitule: String,
			from: Date,
			to: Date,
			title: String,
			description: String
		}
	],
	cv: [
		{
			intitule: String,
			from: Date,
			to: Date,
			title: String,
			description: String
		}
	],
	majorDescription: {
		type: String
	},
	profilePicture: {
		type: String,
		validate: urlValidator
	},
	backgroundPicture: {
		type: String,
		validate: urlValidator
	},
	rating: {
		totalRating: { type: Number, default: 0 },
		ponctualiteRating: { type: Number, default: 0 },
		communicationRating: { type: Number, default: 0 },
		competencesRating: { type: Number, default: 0 },
		count: { type: Number, default: 0 }
	},
	rated: [
		{
			type: ObjectId,
			ref: 'User'
		}
	],
	comments: [
		{
			title: String,
			body: String,
			totalRating: Number,
			author: {
				fullName: String,
				_id: {
					type: ObjectId,
					ref: 'User',
				}
			}
		}
	],
	subjects: [
		{
			type: ObjectId,
			ref: 'Subject',
			validate: subjectValidator
		}
	],
	asso: {
		type: ObjectId,
		ref: "Asso"
	},
	givenToAsso: [
		{
			asso: {
				type: ObjectId,
				ref: "Asso"
			},
			totalAmount: {
				type: Number,
				default: 0
			}
		}
	],
	siretNumber: String,
	companyAddress: String,
	schedule: [
		{
			day: Number,
			periods: [[String]]
		}
	]
});

tutorSchema.plugin(mongooseAggregatePaginate);
tutorSchema.index({ "loc": "2dsphere" });
var Tutor = User.discriminator('Tutor', tutorSchema);


module.exports = {
	Tutor
};
```

Thank you for your time !! Any help would be greatly appreciated

**Comment by GeorgeAnanthSoosai** [comment] 2018-08-14 16:31
same issue here.. Any update on this one ?

**Comment by GeorgeAnanthSoosai** [comment] 2018-08-14 16:33
sorting works very first page.. and sopped working when going next page.. not sure why sorting is not working there.. its so wired

**Comment by ldevalbray** [comment] 2018-08-15 14:31
No updates ... Still unsolved :(

**Comment by realmike33** [comment] 2018-08-22 21:38
Im sure this project is dead. Luckily this is open source and you can just modify the code yourself.

**Comment by Maheshkumar-Kakade** [comment] 2018-08-23 06:39
No, it is not dead. You can contribute to this project. I was not able to reproduce issue hence not able to fix it. If you manage to fix it then please send me PR. OR you can send me dummy data to reproduce it.

**Comment by abhishek0494** [comment] 2018-12-23 13:41
This is happening because the field you are sorting with is not unique

refer this
https://stackoverflow.com/questions/44692075/mongo-db-duplication-issue-while-using-sorting-with-limit-and-skip-in-aggregatio

**Comment by Maheshkumar-Kakade** [comment] 2019-02-10 13:21
I am closing this issue. @abhishek0494 explained the reason for the same.

**Closed by Maheshkumar-Kakade** 2019-02-10 13:21 UTC
